import type { Product, Category, SortOption } from "../types/product";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "SWEAT COL ZIPPÉ BASIQUE",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 26264,
    originalPrice: 26264,
    image: "/article-un.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Sweat col zippé basique en coton",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Noir", "Gris", "Blanc", "Marine", "Beige", "Vert"],
    colorVariants: 6,
    stockStatus: "in_stock",
    availableStock: 45,
    rating: 4.5,
    reviewCount: 23,
  },
  {
    id: 2,
    name: "SANDALES À DOUBLE BRIDE",
    category: "CHAUSSURES",
    categoryId: 2,
    price: 19672,
    originalPrice: 19672,
    image: "/article-deux.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Sandales à double bride confortables",
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["Noir"],
    stockStatus: "in_stock",
    availableStock: 32,
    rating: 4.2,
    reviewCount: 15,
  },
  {
    id: 3,
    name: "T-SHIRT IMPRIMÉ BIMATIÈRE",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 15078,
    originalPrice: 15078,
    image: "/article-trois.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "T-shirt imprimé bimatière moderne",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gris foncé", "Noir"],
    stockStatus: "in_stock",
    availableStock: 78,
    rating: 4.3,
    reviewCount: 31,
  },
  {
    id: 4,
    name: "SANDALES À BRIDES",
    category: "CHAUSSURES",
    categoryId: 2,
    price: 19672,
    originalPrice: 19672,
    image: "/article-quatre.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Sandales à brides élégantes",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Noir"],
    stockStatus: "in_stock",
    availableStock: 28,
    rating: 4.4,
    reviewCount: 19,
  },
  {
    id: 5,
    name: "ROBE SCULPTURALE NOIR",
    category: "HAUTE COUTURE",
    categoryId: 3,
    price: 59114,
    originalPrice: 85395,
    image: "/article-dix-neuf.jpg",
    isNew: true,
    isSale: true,
    discountPercentage: 31,
    description: "Robe sculpturale en soie noire avec drapage asymétrique",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Noir", "Bordeaux"],
    stockStatus: "low_stock",
    availableStock: 5,
    rating: 4.8,
    reviewCount: 12,
  },
  {
    id: 6,
    name: "BLOUSE SOIE PREMIUM",
    category: "SIGNATURE",
    categoryId: 4,
    price: 45962,
    originalPrice: 45962,
    image: "/article-cinq.jpg",
    isNew: true,
    isSale: false,
    discountPercentage: 0,
    description: "Blouse en soie pure avec col chemisier",
    sizes: ["S", "M", "L"],
    colors: ["Blanc", "Ecru", "Noir"],
    stockStatus: "in_stock",
    availableStock: 18,
    rating: 4.9,
    reviewCount: 8,
  },
  {
    id: 7,
    name: "JUPE PLISSÉE",
    category: "AVANT-GARDE",
    categoryId: 5,
    price: 32827,
    originalPrice: 43330,
    image: "/article-six.jpg",
    isNew: false,
    isSale: true,
    discountPercentage: 24,
    description: "Jupe plissée à taille haute",
    sizes: ["XS", "S", "M"],
    colors: ["Noir", "Gris", "Bleu nuit"],
    stockStatus: "in_stock",
    availableStock: 22,
    rating: 4.6,
    reviewCount: 27,
  },
  {
    id: 8,
    name: "SAC À MAIN STRUCTURÉ",
    category: "EXCLUSIVITÉ",
    categoryId: 6,
    price: 78834,
    originalPrice: 78834,
    image: "/sac-a-main.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Sac à main structuré en cuir pleine fleur",
    sizes: ["Unique"],
    colors: ["Noir", "Camel"],
    stockStatus: "in_stock",
    availableStock: 12,
    rating: 4.7,
    reviewCount: 34,
  },
  {
    id: 9,
    name: "PULL EN MAILLE",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 30196,
    originalPrice: 30196,
    image: "/article-sept.jpg",
    isNew: true,
    isSale: false,
    discountPercentage: 0,
    description: "Pull en maille douce et confortable",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Noir", "Gris"],
    stockStatus: "in_stock",
    availableStock: 35,
    rating: 4.5,
    reviewCount: 21,
  },
  {
    id: 10,
    name: "BOTTINES EN CUIR",
    category: "CHAUSSURES",
    categoryId: 2,
    price: 59114,
    originalPrice: 78834,
    image: "/article-huit.jpg",
    isNew: false,
    isSale: true,
    discountPercentage: 25,
    description: "Bottines en cuir véritable",
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["Noir", "Marron"],
    stockStatus: "in_stock",
    availableStock: 15,
    rating: 4.4,
    reviewCount: 42,
  },
  {
    id: 11,
    name: "CHEMISE OVERSIZE",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 26264,
    originalPrice: 26264,
    image: "/article-neuf.jpg",
    isNew: true,
    isSale: false,
    discountPercentage: 0,
    description: "Chemise oversize en coton",
    sizes: ["S", "M", "L"],
    colors: ["Blanc", "Bleu", "Rayé"],
    stockStatus: "in_stock",
    availableStock: 42,
    rating: 4.3,
    reviewCount: 17,
  },
  {
    id: 12,
    name: "PANTALON TAILLEUR",
    category: "PRÊT-À-PORTER",
    categoryId: 7,
    price: 39396,
    originalPrice: 39396,
    image: "/article-dix.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Pantalon tailleur coupe droite",
    sizes: ["34", "36", "38", "40", "42"],
    colors: ["Noir", "Gris", "Beige"],
    stockStatus: "in_stock",
    availableStock: 25,
    rating: 4.5,
    reviewCount: 29,
  },
  {
    id: 13,
    name: "MANTEAU LONG",
    category: "OUTERWEAR",
    categoryId: 8,
    price: 98535,
    originalPrice: 131380,
    image: "/article-onze.jpg",
    isNew: true,
    isSale: true,
    discountPercentage: 25,
    description: "Manteau long en laine mélangée",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Camel", "Noir", "Gris"],
    stockStatus: "low_stock",
    availableStock: 7,
    rating: 4.9,
    reviewCount: 11,
  },
  {
    id: 14,
    name: "BASKETS MINIMALISTES",
    category: "CHAUSSURES",
    categoryId: 2,
    price: 52545,
    originalPrice: 52545,
    image: "/article-douze.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Baskets minimalistes en cuir",
    sizes: ["36", "37", "38", "39", "40", "41", "42"],
    colors: ["Blanc", "Noir"],
    stockStatus: "in_stock",
    availableStock: 52,
    rating: 4.6,
    reviewCount: 38,
  },
  {
    id: 15,
    name: "ÉCHARPE EN LAINE",
    category: "ACCESSOIRES",
    categoryId: 9,
    price: 23627,
    originalPrice: 32827,
    image: "/article-treize.jpg",
    isNew: false,
    isSale: true,
    discountPercentage: 28,
    description: "Écharpe douce en laine mérinos",
    sizes: ["Unique"],
    colors: ["Beige", "Gris", "Noir", "Bordeaux"],
    stockStatus: "in_stock",
    availableStock: 63,
    rating: 4.2,
    reviewCount: 45,
  },
  {
    id: 16,
    name: "ROBE MIDI FLUIDE",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 45962,
    originalPrice: 45962,
    image: "/article-quatorze.jpg",
    isNew: true,
    isSale: false,
    discountPercentage: 0,
    description: "Robe midi fluide pour toute occasion",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Noir", "Bleu nuit", "Bordeaux"],
    stockStatus: "in_stock",
    availableStock: 19,
    rating: 4.7,
    reviewCount: 14,
  },
  {
    id: 17,
    name: "BLOUSON EN CUIR",
    category: "OUTERWEAR",
    categoryId: 8,
    price: 131380,
    originalPrice: 164225,
    image: "/article-quinze.jpg",
    isNew: false,
    isSale: true,
    discountPercentage: 20,
    description: "Blouson en cuir véritable",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Noir", "Marron"],
    stockStatus: "in_stock",
    availableStock: 9,
    rating: 4.8,
    reviewCount: 22,
  },
  {
    id: 18,
    name: "LUNETTES DE SOLEIL",
    category: "ACCESSOIRES",
    categoryId: 9,
    price: 32827,
    originalPrice: 32827,
    image: "/article-seize.jpg",
    isNew: true,
    isSale: false,
    discountPercentage: 0,
    description: "Lunettes de soleil design moderne",
    sizes: ["Unique"],
    colors: ["Noir", "Écaille"],
    stockStatus: "in_stock",
    availableStock: 31,
    rating: 4.4,
    reviewCount: 26,
  },
  {
    id: 19,
    name: "JEAN SLIM FIT",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 39396,
    originalPrice: 39396,
    image: "/article-dix-sept.jpg",
    isNew: false,
    isSale: false,
    discountPercentage: 0,
    description: "Jean slim fit confortable",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Bleu foncé", "Noir", "Gris"],
    stockStatus: "in_stock",
    availableStock: 48,
    rating: 4.5,
    reviewCount: 33,
  },
  {
    id: 20,
    name: "CARDIGAN LONG",
    category: "VÊTEMENTS",
    categoryId: 1,
    price: 45962,
    originalPrice: 59114,
    image: "/article-dix-huit.jpg",
    isNew: true,
    isSale: true,
    discountPercentage: 22,
    description: "Cardigan long en maille fine",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Beige", "Gris", "Noir"],
    stockStatus: "in_stock",
    availableStock: 14,
    rating: 4.6,
    reviewCount: 18,
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "VÊTEMENTS",
    count: 8,
    subcategories: [
      { id: 101, name: "T-shirts", count: 3, parentId: 1 },
      { id: 102, name: "Robes", count: 2, parentId: 1 },
      { id: 103, name: "Pulls", count: 2, parentId: 1 },
      { id: 104, name: "Jeans", count: 1, parentId: 1 },
    ],
  },
  {
    id: 2,
    name: "CHAUSSURES",
    count: 5,
    subcategories: [
      { id: 201, name: "Sandales", count: 2, parentId: 2 },
      { id: 202, name: "Bottines", count: 1, parentId: 2 },
      { id: 203, name: "Baskets", count: 1, parentId: 2 },
    ],
  },
  {
    id: 3,
    name: "HAUTE COUTURE",
    count: 1,
  },
  {
    id: 4,
    name: "SIGNATURE",
    count: 1,
  },
  {
    id: 5,
    name: "AVANT-GARDE",
    count: 1,
  },
  {
    id: 6,
    name: "EXCLUSIVITÉ",
    count: 1,
  },
  {
    id: 7,
    name: "PRÊT-À-PORTER",
    count: 1,
  },
  {
    id: 8,
    name: "OUTERWEAR",
    count: 2,
  },
  {
    id: 9,
    name: "ACCESSOIRES",
    count: 2,
  },
];

export const SORT_OPTIONS: { value: SortOption; label: string }[] = [
  { value: "featured", label: "En vedette" },
  { value: "newest", label: "Nouveautés" },
  { value: "price-asc", label: "Prix croissant" },
  { value: "price-desc", label: "Prix décroissant" },
  { value: "discount", label: "Meilleures réductions" },
  { value: "rating", label: "Mieux notés" },
  { value: "popularity", label: "Popularité" },
];

export const ITEMS_PER_PAGE = 8;
export const INITIAL_PRICE_RANGE = { min: 0, max: 250000 };
